### ISSUE TITLE
UNICEF Feature 2

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/OTTAAProject#10]
We need a second feature for UNICEF

Add a magnifying glass in the group gallery that allows you to quickly find a picto and select it to add to the sentence.

- [x]  Add magnifying glass into the UI, right next to the CircularButton
- [x]  Create the SearchView and add a search functionality in the group ALL.
- [x]  Show Pictogram that matches the search in a Dialog or similar.
- [x]  Offer ARASAAC Pictogram if an internet connection is available.
- [x] Change ARASAAC Logo for a better one in Galeria ARASAAC
- [x]  add pictogram to the group all

**Comment by hectoritr** [comment]
Add a magnifying glass in the group gallery that allows you to quickly find a picto and select it to add to the sentence.

- [ ] Add magnifying glass into the UI, right next to the CircularButton
- [ ] Create the SearchView and add a search functionality in the group ALL.
- [ ] Show Pictogram that matches the search in a Dialog or similar.
- [ ] Offer ARASAAC Pictogram if an internet connection is available.

**Comment by gonojuarez** [comment]
we need to edit the findallpictograms interface XML
