### ISSUE TITLE
Error when creating a new picto

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/OTTAAProject#103]
**To Reproduce**
1. Go to Create Picto
2. Click on Camara

**Screenshots**
1. 
![1](https://user-images.githubusercontent.com/78824577/142449329-7c4ced44-6a08-4e4f-9a2b-e399d82d2fe9.PNG)
2. 
![2](https://user-images.githubusercontent.com/78824577/142449380-3ed4f73d-95bb-49a8-9873-e0e9e83db94e.PNG)
3. 
![3](https://user-images.githubusercontent.com/78824577/142449436-7c695a61-dba6-4803-bb67-45169ad356bb.PNG)
4.
![4](https://user-images.githubusercontent.com/78824577/142449464-35ccdf89-e36d-4210-8254-51d1a3b10d0d.PNG)

**Smartphone (please complete the following information):**
 - Device: Kanji
 - OS: 
 - Version:

**Additional context**
-

**Comment by gonojuarez** [comment]
I found this error happen in android 9 and after because is a file provider conflict.
to solve that when I change the authorities at the manifest
`        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="com.stonefacesoft.ottaaproject.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true"
            tools:replace="android:authorities"
            >
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths" />
        </provider>
`
by that 
`        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true"
            tools:replace="android:authorities"
            >
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths" />
        </provider>
`
after that, I edit the file "file_paths".
at this file, I changed the following lines
 `  <external-path name="my_images" path="Android/data/com.stonefacesoft.ottaa/files/Pictures" />
  <external-path name="my_images_debug" path="Android/data/com.stonefacesoft.ottaa.debug/files/Pictures" />`

by this
 '<files-path
    name="my_images"
    path="images/" />

<files-path
    name="my_docs"
    path="docs/" />

<external-files-path
    name="external_files_dir"
    path="/" />

<cache-path
    name="cache_dir"
    path="/" />

<external-cache-path
    name="external_cache_dir"
    path="/" />

<external-media-path
    name="external_media_dir"
    path="/" />

<external-media-path
    name="external_media_dir"
    path="/" />'

**Comment by gonojuarez** [comment]
after that, I edit the file "file_paths".
at this file, I changed the following lines
 ` 
 <external-path name="my_images" path="Android/data/com.stonefacesoft.ottaa/files/Pictures" />
  <external-path name="my_images_debug" path="Android/data/com.stonefacesoft.ottaa.debug/files/Pictures" />`

by this `
<files-path
    name="my_images"
    path="images/" />

<files-path
    name="my_docs"
    path="docs/" />

<external-files-path
    name="external_files_dir"
    path="/" />

<cache-path
    name="cache_dir"
    path="/" />

<external-cache-path
    name="external_cache_dir"
    path="/" />

<external-media-path
    name="external_media_dir"
    path="/" />

<external-media-path
    name="external_media_dir"
    path="/" /> `
