### ISSUE TITLE
Crash when Entering the App

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/OTTAAProject#104]
**Describe the bug**
The app chrashes when the user tries to open in.

**To Reproduce**
1. Touch OTTAA Project's icon in the launcher

**Expected behavior**
After touching the app's icon, the screen will turn white and OTTAA's logo will be shown in the middle of the screen, 
below the logo, it will appear "Iniciando sesión", then "Cargando datos del usuario" and then the app will crash and
will show the failure message attached below.

**Screenshots**

![bug inicio](https://user-images.githubusercontent.com/78824577/142447750-d964c492-ea98-421c-a6c4-06f267fd8975.PNG)

**Smartphone (please complete the following information):**
 - Device: Lenovo Tab M10
 - OS: 
 - Version: 7.6.4

**Comment by gonojuarez** [comment]
I found another error related to the user name.
The system makes a request to firebase about the user name.
And the name is not ready or uploaded to the firebase database.

**Comment by gonojuarez** [comment]
I add a method that verifies if the userData class exist else the system creates it.
   ```
 public DataUser getUserData() {
        if(userData == null)
            userData = new DataUser();
        return userData;
    }
```
