### ISSUE TITLE
Custom pictograms and groups are not shown in Gallery

### ISSUE THREAD

**Issue by scioffi96** [OTTAA-Project/OTTAAProject#105]
**Describe the bug**
After a few hours of creating a custom picto, it wont be shown in gallery.

**To Reproduce**
1. Create a new picto from gallery.
2. Wait a few hours.
3. Go to gallery and search for that custom picto.

**Expected behavior**
You wont find the custom picto you created previously.

**Smartphone (please complete the following information):**
 - Device: SM-T500 and Lenovo TB-X606X.
 - OS: Android 11 and unknowkn respectively
 - Version: 91 and 93 respectively

**Additional context**
It seems that custom pictograms are saved but are not shown in gallery, because we saw a few custom pictos recommended at the beggining of the app but we couldnt find them in gallery. 
It's difficult to be sure, because new pictograms are not going to be recommended.

*New*
Another user reported that Custom Groups are not shown in gallery either after a few hours.

**Comment by gonojuarez** [comment]
This error happens at the main activity when the application doesn't read correctly the groups or pictograms.
At this point, OTTAA tries to download all files again.
The application fails when trying to save pictograms or groups.

I delete these lines
                 ```
        mStorageRefGrupos = FirebaseStorage.getInstance().getReference().child("Archivos_Paises/grupos/" + "grupos_" + locale + "." + "txt");
                                final File gruposUsuarioFile = new File(roothPath, Constants.ARCHIVO_GRUPOS);
                                mStorageRefGrupos.getFile(gruposUsuarioFile).addOnSuccessListener(new OnSuccessListener<FileDownloadTask.TaskSnapshot>() {
                                    @Override
                                    public void onSuccess(FileDownloadTask.TaskSnapshot taskSnapshot) {
                                        try {
                                            json.setmJSONArrayTodosLosGrupos(json.readJSONArrayFromFile(gruposUsuarioFile.getAbsolutePath()));
                                            if (!json.guardarJson(Constants.ARCHIVO_GRUPOS)) {
                                                Log.e(TAG, "Fallo al guardar json");
                                            }else{
                                                Log.e(TAG, "Grupo json");
                                                gruposUsuarioFile.delete();
                                            }
                                            observableInteger.set(observableInteger.get() + 1);
                                        } catch (Exception ex) {

                                        }
                                    }

                                });

```
