### ISSUE TITLE
Some words are still in spanish despite changing the language

### ISSUE THREAD

**Issue by scioffi96** [OTTAA-Project/OTTAAProject#121]
**Describe the bug**
Once you change the language (I changed from spanish to english) and go to Generate report, the language doesnt change in every senteces.  In games there still the sentence "A jugar!", which isnt translated either, the same happens when I want to share a picto/phrase with the word "Texto", in Group gallery with the word "Galería grupos", in Accesibility, and with every tag while editing a picto (eg: "mañana, tarde, noche") (screenshots attached).

**To Reproduce**
1. Go to 'Configuración'
2. Click on 'Idioma', 'Selecciona un idioma' and chose "English"
3. Go to the the sections described above. 

**Expected behavior**
What should happen is that every word should be in english (and start with a capital letter too at the begining of the sentence).

**Screenshots**

![tag](https://user-images.githubusercontent.com/78824577/150793020-0d715939-7195-4af2-b482-e9baec4049dc.jpeg)
![tag (2)](https://user-images.githubusercontent.com/78824577/150793025-5e30b856-1472-483c-b5b7-ff9ca72cf21a.jpeg)
![acc](https://user-images.githubusercontent.com/78824577/150793028-d0c702a5-6db0-483a-a326-a90eaf20e43c.jpeg)
![settings](https://user-images.githubusercontent.com/78824577/150793031-96154ad7-e445-4e71-81c0-e16d4cf580ed.jpeg)
![inform](https://user-images.githubusercontent.com/78824577/150793033-917608a1-7bbd-469f-93fc-4b70a68d0b3b.jpeg)
![share](https://user-images.githubusercontent.com/78824577/150793034-92762c50-1991-458e-8de2-22c29c84f038.jpeg)
![games](https://user-images.githubusercontent.com/78824577/150793036-294a7595-99cb-46d9-a193-cde20f1e18e7.jpeg)
![gallery](https://user-images.githubusercontent.com/78824577/150793038-ae02387a-ea81-4a15-ace5-df8466f51f84.jpeg)

**Smartphone (please complete the following information):**
 - Device: Samsung A8
 - OS: 9
 - Version 96

**Comment by gonojuarez** [comment]
solved
