### ISSUE TITLE
[Feat]: Tell a story

### ISSUE THREAD

**Issue by gonojuarez** [OTTAA-Project/OTTAAProject#181]
### Contact Details

gonojuarez17@gmail.com

### What is this about?

For storytelling game:
The main idea is that the user will be able to add up to 4 pictograms to create their own story.
For this, they will have to choose first a character for their story.

- [x]  Reuse code from the Boards Tab chooser and filter out a set of boards (People, Animals, Toys, etc)
- [x]  They first choose the board, and then the Pictogram

Then, they will choose a modifier.

- [x]  Reuse code from the Boards Tab chooser and filter out a set of boards (Colors, adjectives, feelings)
- [x]  They first choose the board, and then the Pictogram

After that, they choose an action
- [x]  Reuse code from the Boards Tab chooser and filter out a set of boards (Actions)
- [x]  They first choose the board, and then the Pictogram
And finally, they choose a place

- [x]  Reuse code from the Boards Tab chooser and filter out a set of boards (Actions)
- [x]  They first choose the board, and then the Pictogram

When all this is done, they go to the next screen and create the story @lopezjuanma96 will help here with the prompt.
The user needs to listen to the story every time they press the "Talk button"
For later features, we will add Save stories and Share stories.

### Where do you want to see this implemented?

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lopezjuanma96** [comment]
I've been testing some prompts, here are the results:

<hr>

Create a short story (2 or 3 sentences) in english using the words in this sequence as subjects or themes. Use the words in order. The main character is "mom".
"want to", "play", "ball", "park"

**Temperature:** .7

_Mom wanted to take her kids to the park to play ball. She had been looking forward to this all week and was so excited to finally get out and have some fun._

**Temperature:** .0

_Mom wanted to take her kids to the park to play ball. She was excited to spend the day with them, and they were equally excited to get out of the house and have some fun._

<hr>

Use this words to create a short story (2 or 3 sentences long) where the main character is "mom". Keep the words in order and spread through the story (don't use them all at once).
"want to", "play", "ball", "park"

**Temperature:** .7

_Mom wanted to take her kids to the park to play ball. She hoped they would have a great time in the sun and get some exercise._

**Temperature:** .0

_Mom wanted to take her kids to the park to play ball. She was excited to spend the day outside with her family and enjoy the sunshine._

<hr>

Complete the missing words to create a short story (2 or 3 sentences long) with this words. It is crutial to keep the order of the words in their appeareance in the story. The main character is mom.
"want to", "play", "ball", "park"

**Temperature:** .7

_Mom wanted to take the kids to the park to play ball. She was so excited to spend the day in the sun, playing together as a family._

**Temperature:** .0

_Mom wanted to take her kids to the park to play ball. She was excited to spend the day with them and have some fun in the sun._

<hr>

Is it something like that what we want @hectoritr ? Most results are similar, it seems to be important to ask GPT to crutially keep the words in order. I'll test with other sequences of words later, I used the same in all of them to compare more easily.

**Comment by lopezjuanma96** [comment]
We were talking with Hector and made some changes to the prompt to get a better and longer result, this would be the prompt we'll be using for now:

**Prompt:** Act as a kindergarten teacher and write a story in {language} for kids using the following words. "{pictos}".
**Temperature:** 0.7
**Max Tokens:** 1000
**Model:** text-davinci-003

So for example, using:

_Act as a kindergarten teacher and write a story in Spanish for kids using the following words. 
"tomato, pink, dance, kitchen"_

We got:

Un día, había una tomatita muy especial. Estaba de color rosa brillante y le encantaba bailar. La tomatita salió a bailar a la cocina. Se movió y se balanceó al ritmo de la música. Se movió hacia la derecha y hacia la izquierda, y dio algunos saltitos.

Entonces, la tomatita se encontró con una zanahoria. La zanahoria estaba muy sorprendida de ver a una tomatita bailando. La zanahoria le dijo: "¿Por qué estás bailando, Tomatita?" 

La tomatita le respondió: "¡Estoy bailando porque me gusta mucho! ¡Es mi forma favorita de divertirme!"

La zanahoria sonrió y dijo: "¡Eso es genial! ¿Quieres bailar conmigo?"

La tomatita dijo: "¡Claro que sí!" Y de inmediato comenzaron a bailar juntos. Bailaron y bailaron hasta que la tomatita se cansó. 

Entonces la tomatita saludó a la zanahoria y se fue a descansar. ¡La tomatita rosa había tenido un gran día bailando en la cocina!
