### ISSUE TITLE
Error bugs on Screen resolution

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/OTTAAProject#48]
**Describe the bug**
There are some errors in the newly designed interface on a mobile phone like One Plus 6. 

**To Reproduce**
Open the app on one if these devices. 

**Expected behavior**
The UI should be pixel-perfect.

**Screenshots**
https://www.dropbox.com/s/ny36s587f5b1u56/WhatsApp%20Image%202021-05-26%20at%2015.31.03.jpeg?dl=0
https://www.dropbox.com/s/os3qcfda858j186/WhatsApp%20Image%202021-05-26%20at%2015.29.57.jpeg?dl=0

**Smartphone (please complete the following information):**
 - Device: One Plus 6
 - OS: -
 - Version v83
**Additional context**
We found the error in devices with Hdpi resolution 400x800 .

**Comment by gonojuarez** [comment]
![Uploading Screenshot_1622814271.png…]()

**Comment by gonojuarez** [comment]
![Screenshot_1622814244](https://user-images.githubusercontent.com/9198172/120811639-92f4aa80-c522-11eb-8ca4-1fe227569a85.png)
![Screenshot_1622814239](https://user-images.githubusercontent.com/9198172/120811641-938d4100-c522-11eb-87e6-0179532a1633.png)
![Uploading Screenshot_1622814222.png…]()

**Comment by gonojuarez** [comment]
![Screenshot_1622814271](https://user-images.githubusercontent.com/9198172/120811922-e830bc00-c522-11eb-86ea-40262c579267.png)
![Screenshot_1622814244](https://user-images.githubusercontent.com/9198172/120811926-e961e900-c522-11eb-81fb-4c04350303b4.png)
![Screenshot_1622814239](https://user-images.githubusercontent.com/9198172/120811927-e961e900-c522-11eb-8410-58c9c5d6f3fc.png)
![Screenshot_1622814222](https://user-images.githubusercontent.com/9198172/120811928-e9fa7f80-c522-11eb-8334-06e08ac922b9.png)
![Screenshot_1622814207](https://user-images.githubusercontent.com/9198172/120811929-e9fa7f80-c522-11eb-9e06-14a67ee5a4a4.png)
![Screenshot_1622814193](https://user-images.githubusercontent.com/9198172/120811930-ea931600-c522-11eb-92a9-cd935ddbf2a4.png)
![Screenshot_1622814162](https://user-images.githubusercontent.com/9198172/120811933-ea931600-c522-11eb-81a3-7145b0d43c6a.png)
![Screenshot_1622814154](https://user-images.githubusercontent.com/9198172/120811935-eb2bac80-c522-11eb-8cbb-75dfd9d92814.png)
![Screenshot_1622814098](https://user-images.githubusercontent.com/9198172/120811936-ebc44300-c522-11eb-9db4-599e20a676d5.png)
![Screenshot_1622814076](https://user-images.githubusercontent.com/9198172/120811938-ebc44300-c522-11eb-892c-2ac8ce0a03a4.png)
![Screenshot_1622814069](https://user-images.githubusercontent.com/9198172/120811940-ec5cd980-c522-11eb-8e48-69f3db4349c2.png)
![Screenshot_1622814047](https://user-images.githubusercontent.com/9198172/120811941-ec5cd980-c522-11eb-8493-8a4ea6ca120d.png)
![Screenshot_1622814034](https://user-images.githubusercontent.com/9198172/120811943-ecf57000-c522-11eb-9943-045357ec33c6.png)
![Screenshot_1622813992](https://user-images.githubusercontent.com/9198172/120811945-ecf57000-c522-11eb-9cb9-4cde560199a6.png)
![Screenshot_1622813982](https://user-images.githubusercontent.com/9198172/120811949-ed8e0680-c522-11eb-9464-e93720a42b0f.png)
