### ISSUE TITLE
Change Tutorial for Login Activity 3

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/OTTAAProject#67]
**Is your feature request related to a problem? Please describe.**
Offer the user a way to learn about OTTAA until the learning center is done.

**Action Plan**
Add a TO-DO list of thing you need to complete in order to successfully finish this development.

- [x] Point Tutorial on Navigation bar to Login Activity 3 so the user can ask for a demo, ask AWO

**Comment by gonojuarez** [comment]
the tutorial navigation was updated to the new design in order to maintain the application with the new parameters
