### ISSUE TITLE
Picto Sugeridos not working

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/OTTAAProject#90]
**Describe the bug**
The app is not downloading the suggested pictos, only works when the user chooses the Gender and Age from Settings, it should work with the information the user inputs in the Login process. 

**Expected behavior**
When the user activates the PictoSugeridos option it should download the right suggested files and show the suggested pictograms. 

**Smartphone (please complete the following information):**
- All devices

**Comment by gonojuarez** [comment]
- [ ] Gender Pictogram list
- [ ] Download Suggested Pictograms
