### ISSUE TITLE
Preference Get User Uid error

### ISSUE THREAD

**Issue by gonojuarez** [OTTAA-Project/OTTAAProject#91]
**Description**
A bug is a firebase crashlytics report
the system show this message:

Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.stonefacesoft.ottaa/com.stonefacesoft.ottaa.Principal}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.auth.g.j0()' on a null object referenceshow

**Comment by hectoritr** [comment]
tag 6.7.5
